# Generated by Django 3.2.3 on 2021-05-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differential_pressure', models.IntegerField()),
                ('temprature', models.IntegerField()),
                ('relative_humidity', models.IntegerField()),
            ],
        ),
    ]
