# Generated by Django 3.2.3 on 2021-05-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airiq_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopperSilver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_material', models.CharField(max_length=20)),
                ('amo', models.IntegerField()),
                ('corrosion_rate', models.CharField(max_length=10)),
            ],
        ),
    ]
