# Generated by Django 3.2.3 on 2021-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airiq_app', '0002_coppersilver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='differential_pressure',
            field=models.FloatField(),
        ),
    ]
